version: "3.8"

services:
  nginx:
    image: nginx
    volumes:
      - static_volume:/app/web/quantummanagementapp/static
      - media_volume:/app/web/media/images
    ports:
      - 1337:8020
    depends_on:
      - web
  web:
    build: .
    command: gunicorn quantummanagement.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static_volume:/app/web/quantummanagementapp/static
      - media_volume:/app/web/media/images
    environment:
      DJANGO_SETTINGS_MODULE: quantummanagement.settings
      POSTGRES_DB: quantumdb
      POSTGRES_USER: matthewcrook
      POSTGRES_PASSWORD: password
      DB_HOST: db
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume:
