version: "3.8"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static_volume:/app/web/quantummanagementapp/static
      - media_volume:/app/web/media/images
    environment:
      DJANGO_SETTINGS_MODULE: quantummanagement.settings
      DEBUG: True
      ENVIRONMENT: "development"
    env_file:
      - ./.env

volumes:
  static_volume:
  media_volume:
