# Generated by Django 3.0.7 on 2020-06-15 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adminUser',
                'verbose_name_plural': 'adminUsers',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('current_operating_capacity', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'attraction',
                'verbose_name_plural': 'attractions',
            },
        ),
        migrations.CreateModel(
            name='AttractionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'attractiontype',
                'verbose_name_plural': 'attractiontypes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_salary', models.BooleanField(blank=True, null=True)),
                ('is_hourly', models.BooleanField(blank=True, null=True)),
                ('admin_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.AdminUser')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('start_date'), descending=True, nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('max_capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_attractions', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'park',
                'verbose_name_plural': 'parks',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'visitor',
                'verbose_name_plural': 'visitors',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('check_in'), nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='VisitorCheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('checkout_timestamp'), descending=True, nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='ParkAttractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='quantummanagementapp.Attraction')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkinfo', to='quantummanagementapp.Park')),
            ],
            options={
                'verbose_name': 'parkAttraction',
                'verbose_name_plural': 'parkAttractions',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction', to='quantummanagementapp.Attraction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='quantummanagementapp.Employee')),
            ],
            options={
                'verbose_name': 'employeeattraction',
                'verbose_name_plural': 'employeeattractions',
            },
        ),
        migrations.CreateModel(
            name='AttractionWaitTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_wait_time', models.DurationField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Attraction')),
            ],
            options={
                'verbose_name': 'waittime',
                'verbose_name_plural': 'waittimes',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('current_wait_time'), descending=True, nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='AttractionVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Attraction')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('visit_timestamp'), descending=True, nulls_last=True),),
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.AttractionType'),
        ),
    ]
