# Generated by Django 3.0.14 on 2021-07-30 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.forms.widgets
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'adminUser',
                'verbose_name_plural': 'adminUsers',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('current_operating_capacity', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'attraction',
                'verbose_name_plural': 'attractions',
            },
        ),
        migrations.CreateModel(
            name='AttractionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'attractiontype',
                'verbose_name_plural': 'attractiontypes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pay_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.AdminUser')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('start_date'), descending=True, nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name=django.forms.widgets.ClearableFileInput)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('max_capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_attractions', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'park',
                'verbose_name_plural': 'parks',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='VisitorCheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_timestamp', models.DateTimeField(auto_now_add=True)),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Park')),
            ],
            options={
                'verbose_name': 'visitorcheckout',
                'verbose_name_plural': 'visitorcheckouts',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('checkout_timestamp'), descending=True, nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Park')),
            ],
            options={
                'verbose_name': 'visitor',
                'verbose_name_plural': 'visitors',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('check_in'), nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='ParkAttractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='quantummanagementapp.Attraction')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkinfo', to='quantummanagementapp.Park')),
            ],
            options={
                'verbose_name': 'parkAttraction',
                'verbose_name_plural': 'parkAttractions',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction', to='quantummanagementapp.Attraction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='quantummanagementapp.Employee')),
            ],
            options={
                'verbose_name': 'employeeattraction',
                'verbose_name_plural': 'employeeattractions',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Park'),
        ),
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.CharField(blank=True, max_length=10000, null=True)),
                ('task', models.CharField(blank=True, max_length=80, null=True)),
                ('updated_time', models.TimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credentials',
                'verbose_name_plural': 'credentials',
            },
        ),
        migrations.CreateModel(
            name='AttractionWaitTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_wait_time', models.DurationField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Attraction')),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Park')),
            ],
            options={
                'verbose_name': 'waittime',
                'verbose_name_plural': 'waittimes',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('current_wait_time'), descending=True, nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='AttractionVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Attraction')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('visit_timestamp'), descending=True, nulls_last=True),),
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Park'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.AttractionType'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Image'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
