# Generated by Django 3.0.7 on 2020-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantummanagementapp', '0003_auto_20200618_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
