# Generated by Django 3.0.7 on 2020-06-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantummanagementapp', '0004_auto_20200618_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantummanagementapp.Park'),
        ),
    ]
