# Generated by Django 3.0.7 on 2020-06-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantummanagementapp', '0007_auto_20200619_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
