# Generated by Django 3.0.7 on 2020-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantummanagementapp', '0011_auto_20200620_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='compensation_currency',
        ),
        migrations.AlterField(
            model_name='employee',
            name='compensation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
