# Generated by Django 3.0.7 on 2020-06-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantummanagementapp', '0012_auto_20200620_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='compensation',
        ),
    ]
