# Generated by Django 3.0.7 on 2020-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantummanagementapp', '0013_remove_employee_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='compensation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
