# Generated by Django 3.0.7 on 2020-06-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantummanagementapp', '0014_employee_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='compensation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
